### ISSUE TITLE
Cannot disable Switch

### ISSUE THREAD

**Issue by AleeeAhmed** [Angads25/Android-LabeledSwitch#15]
How can we disable switch so that user can't change its state ?

**Comment by singhangadin** [comment]
https://github.com/Angads25/android-toggle/blob/release/app/src/main/res/layout/activity_labeled_switch.xml#L128

**Comment by devLaaziz** [comment]
+++

**Comment by singhangadin** [comment]
Hey, just use android:enabled="false" flag to disable the switch.
